name: Build and publish on push master

on:
  push:
    branches:
      - master

jobs:
  master:
    runs-on: ubuntu-latest
    env:
      SNAPSHOT: false

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk

      - name: Gradle build and publish
        run: gradle build publish
        env:
          BASE: ${{ steps.extract_branch.outputs.branch }}
          SNAP: ${{ env.SNAPSHOT }}
          REPO_USER: ${{ secrets.REPO_USER }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}